name: "Setup"
description: "Setup Node.js & PNPM environment and dependencies"

inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true

runs:
  using: "composite"
  steps:
      - name: ⬇️🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.0
      - name: ⬇️🛎 Checkout
        uses: actions/checkout@v7
        with: 
          persist-credentials: false
      - name: ⬇️🥡🟢 Install node & pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: 🐙😺 Check GitHub API Rate Limit
        id: rate_limit
        run: |
          response=$(gh api rate_limit)
          limit=$(echo $response | jq -r '.resources.core.limit')
          remaining=$(echo $response | jq -r '.resources.core.remaining')
          echo "GitHub API Rate Limit: $remaining/$limit"

          if [ "$remaining" -lt 10 ]; then
              exit 1
          fi
        env:
            GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        shell: bash

      - name: ⬇️📦 Install dependencies
        run: |
           export npm_config_build_from_source=false
           pnpm install --no-frozen-lockfile --ignore-scripts
        shell: bash
