/** Clippium data automatically generated by clippium-toolkit */
export default {
	name  : 'image2ascii',
	flags : {
		'input' : {
			type : 'string',
			desc : 'Parameter input of image2ascii',
		},
		'opts' : {
			type : 'string',
			desc : 'Parameter opts of image2ascii',
		},
		'opts-fit' : {
			type : 'string',
			desc : 'Parameter fit of image2ascii',
		},
		'opts-width' : {
			type : 'string',
			desc : 'Parameter width of image2ascii',
		},
		'opts-height' : {
			type : 'string',
			desc : 'Parameter height of image2ascii',
		},
		'opts-aspectRatio' : {
			type : 'number',
			desc : 'Parameter aspectRatio of image2ascii',
		},
		'opts-chars' : {
			type : 'string',
			desc : 'Parameter chars of image2ascii',
		},
		'opts-container' : {
			type : 'string',
			desc : 'Parameter container of image2ascii',
		},
	},
}
