###############################################################################
# RELEASE DOCS
###############################################################################

name: 🚀📚 Release Documentation

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
    DOCS_ID: 'clippium'
    DOCS_DIR: 'build/docs'
    BUILD_CMD: 'pnpm build && pnpm build-doc'

###############################################################################
# JOBS
###############################################################################

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      #########################################################################
      # INIT
      #########################################################################

      - name: ⬇️🛎 Checkout
        uses: actions/checkout@v6
        with: 
          persist-credentials: false
      - name: ⬇️🏃‍♂️ Set up
        uses: ./.github/actions/setup/
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install extra dependencies
        run: pnpm i -g wrangler

      #########################################################################
      # BUILD
      #########################################################################

      - name: 🏗 Build packages
        run: ${{env.BUILD_CMD}}

      ###################################################################
      # BUILD AND DEPLOY
      ###################################################################

      - name: 🌥 Deploy in cloudflare pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{env.DOCS_DIR}} --project-name=${{env.DOCS_ID}}
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: pnpm

###############################################################################
